repos:
  - repo: https://gtlb.jetsoftpro.com/mechanio/magic-cinema
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - pep8-naming
          - flake8-commas