from .directors import directors_bp
from .genres import genres_bp
from .actors import actors_bp
from .movies import movies_bp
from .auditoriums import auditoriums_bp
from .movie_sessions import movie_sessions_bp
from .users import users_bp
from .tickets import tickets_bp
from .auth import auth_bp
